//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\GitHub\Antlr_Grammar\Grammars\UserGrammar\UserGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUserGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class UserGrammarBaseListener : IUserGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.rul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRul([NotNull] UserGrammarParser.RulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.rul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRul([NotNull] UserGrammarParser.RulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicion([NotNull] UserGrammarParser.CondicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicion([NotNull] UserGrammarParser.CondicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.booleanAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanAttribute([NotNull] UserGrammarParser.BooleanAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.booleanAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanAttribute([NotNull] UserGrammarParser.BooleanAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.numericAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericAttribute([NotNull] UserGrammarParser.NumericAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.numericAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericAttribute([NotNull] UserGrammarParser.NumericAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.comparisionNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisionNumeric([NotNull] UserGrammarParser.ComparisionNumericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.comparisionNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisionNumeric([NotNull] UserGrammarParser.ComparisionNumericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserGrammarParser.connector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnector([NotNull] UserGrammarParser.ConnectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserGrammarParser.connector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnector([NotNull] UserGrammarParser.ConnectorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
