//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\GitHub\Antlr_Grammar\Grammars\UserGrammar\UserGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class UserGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, INT=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "INT", 
		"DIGIT"
	};


	public UserGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public UserGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Si'", "'no'", "'es vegetariano'", "'est\u00E1 ingresado'", "'la edad del usuario'", 
		"'es mayor que'", "' y '", "' o '"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "INT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "UserGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static UserGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\v', 'k', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', 
		'\v', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x6', '\n', '\x66', '\n', '\n', '\r', '\n', '\xE', '\n', 
		'g', '\x3', '\v', '\x3', '\v', '\x2', '\x2', '\f', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x2', '\x32', ';', '\x2', 'j', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x3', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x1A', '\x3', '\x2', '\x2', '\x2', '\a', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\t', ',', '\x3', '\x2', '\x2', '\x2', '\v', ';', 
		'\x3', '\x2', '\x2', '\x2', '\r', 'O', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\\', '\x3', '\x2', '\x2', '\x2', '\x11', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\x65', '\x3', '\x2', '\x2', '\x2', '\x15', 'i', '\x3', '\x2', 
		'\x2', '\x2', '\x17', '\x18', '\a', 'U', '\x2', '\x2', '\x18', '\x19', 
		'\a', 'k', '\x2', '\x2', '\x19', '\x4', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x1B', '\a', 'p', '\x2', '\x2', '\x1B', '\x1C', '\a', 'q', '\x2', '\x2', 
		'\x1C', '\x6', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1E', '\a', 'g', 
		'\x2', '\x2', '\x1E', '\x1F', '\a', 'u', '\x2', '\x2', '\x1F', ' ', '\a', 
		'\"', '\x2', '\x2', ' ', '!', '\a', 'x', '\x2', '\x2', '!', '\"', '\a', 
		'g', '\x2', '\x2', '\"', '#', '\a', 'i', '\x2', '\x2', '#', '$', '\a', 
		'g', '\x2', '\x2', '$', '%', '\a', 'v', '\x2', '\x2', '%', '&', '\a', 
		'\x63', '\x2', '\x2', '&', '\'', '\a', 't', '\x2', '\x2', '\'', '(', '\a', 
		'k', '\x2', '\x2', '(', ')', '\a', '\x63', '\x2', '\x2', ')', '*', '\a', 
		'p', '\x2', '\x2', '*', '+', '\a', 'q', '\x2', '\x2', '+', '\b', '\x3', 
		'\x2', '\x2', '\x2', ',', '-', '\a', 'g', '\x2', '\x2', '-', '.', '\a', 
		'u', '\x2', '\x2', '.', '/', '\a', 'v', '\x2', '\x2', '/', '\x30', '\a', 
		'\xE3', '\x2', '\x2', '\x30', '\x31', '\a', '\"', '\x2', '\x2', '\x31', 
		'\x32', '\a', 'k', '\x2', '\x2', '\x32', '\x33', '\a', 'p', '\x2', '\x2', 
		'\x33', '\x34', '\a', 'i', '\x2', '\x2', '\x34', '\x35', '\a', 't', '\x2', 
		'\x2', '\x35', '\x36', '\a', 'g', '\x2', '\x2', '\x36', '\x37', '\a', 
		'u', '\x2', '\x2', '\x37', '\x38', '\a', '\x63', '\x2', '\x2', '\x38', 
		'\x39', '\a', '\x66', '\x2', '\x2', '\x39', ':', '\a', 'q', '\x2', '\x2', 
		':', '\n', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', 'n', '\x2', '\x2', 
		'<', '=', '\a', '\x63', '\x2', '\x2', '=', '>', '\a', '\"', '\x2', '\x2', 
		'>', '?', '\a', 'g', '\x2', '\x2', '?', '@', '\a', '\x66', '\x2', '\x2', 
		'@', '\x41', '\a', '\x63', '\x2', '\x2', '\x41', '\x42', '\a', '\x66', 
		'\x2', '\x2', '\x42', '\x43', '\a', '\"', '\x2', '\x2', '\x43', '\x44', 
		'\a', '\x66', '\x2', '\x2', '\x44', '\x45', '\a', 'g', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'n', '\x2', '\x2', '\x46', 'G', '\a', '\"', '\x2', '\x2', 
		'G', 'H', '\a', 'w', '\x2', '\x2', 'H', 'I', '\a', 'u', '\x2', '\x2', 
		'I', 'J', '\a', 'w', '\x2', '\x2', 'J', 'K', '\a', '\x63', '\x2', '\x2', 
		'K', 'L', '\a', 't', '\x2', '\x2', 'L', 'M', '\a', 'k', '\x2', '\x2', 
		'M', 'N', '\a', 'q', '\x2', '\x2', 'N', '\f', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', 'g', '\x2', '\x2', 'P', 'Q', '\a', 'u', '\x2', '\x2', 
		'Q', 'R', '\a', '\"', '\x2', '\x2', 'R', 'S', '\a', 'o', '\x2', '\x2', 
		'S', 'T', '\a', '\x63', '\x2', '\x2', 'T', 'U', '\a', '{', '\x2', '\x2', 
		'U', 'V', '\a', 'q', '\x2', '\x2', 'V', 'W', '\a', 't', '\x2', '\x2', 
		'W', 'X', '\a', '\"', '\x2', '\x2', 'X', 'Y', '\a', 's', '\x2', '\x2', 
		'Y', 'Z', '\a', 'w', '\x2', '\x2', 'Z', '[', '\a', 'g', '\x2', '\x2', 
		'[', '\xE', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '\"', '\x2', 
		'\x2', ']', '^', '\a', '{', '\x2', '\x2', '^', '_', '\a', '\"', '\x2', 
		'\x2', '_', '\x10', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '\"', 
		'\x2', '\x2', '\x61', '\x62', '\a', 'q', '\x2', '\x2', '\x62', '\x63', 
		'\a', '\"', '\x2', '\x2', '\x63', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x66', '\x5', '\x15', '\v', '\x2', '\x65', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', '\x14', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\t', '\x2', '\x2', '\x2', 'j', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x4', '\x2', 'g', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
