//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Antlr_Grammar\Antlr.Grammar\Grammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.regla"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegla([NotNull] GrammarParser.ReglaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.regla"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegla([NotNull] GrammarParser.ReglaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicion([NotNull] GrammarParser.CondicionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicion([NotNull] GrammarParser.CondicionContext context);
}
} // namespace Antlr.Grammar
